version: '3.9'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env.development
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 8001:3000
    # command: bash -c /usr/src/app/start.sh
  # db-postgres:
  #   image: postgres:15.3-alpine
  #   container_name: dcs-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: testea
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - .:/data/postgres